FSM:
  _: # enabled fsms
    Passive:
      id: 1
    FixStand:
      id: 2
    Velocity:
      id: 3
      type: RLBase

    Mimic_Action_1: # uncomment to enable
      id: 101
      type: Mimic
    Mimic_Action_2:
      id: 102
      type: Mimic
    Mimic_Action_3:
      id: 103
      type: Mimic


  Passive:
    transitions: 
      FixStand: LT + up.on_pressed
    mode: [
      1,1,1,1,1,1,
      1,1,1,1,1,1,
      1,0,0,
      1,1,1,1,1,0,0,
      1,1,1,1,1,0,0,
    ]
    kd: [
      3,3,3,3,3,3,
      3,3,3,3,3,3,
      3,0,0,
      3,3,3,3,3,0,0,  
      3,3,3,3,3,0,0,  
    ]
  FixStand:
    transitions: 
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
    kp: [
      100., 100., 100., 150., 40., 40.,
      100., 100., 100., 150., 40., 40.,
      200,0,0,
      40,40,40,40,40,0,0,
      40,40,40,40,40,0,0,
    ]
    kd: [
      2,2,2,4,2,2,
      2,2,2,4,2,2,
      5,0,0,
      10,10,10,10,10,0,0,
      10,10,10,10,10,0,0,
    ]
    ts: [0, 3]
    qs: [
      [],
      [ -0.1, 0,0,0.3,-0.2,0,
        -0.1, 0,0,0.3,-0.2,0,
        0,0,0,
        0, 0.25,0,0.97,0.15, 0,0,
        0, -0.25,0,0.97,-0.15, 0,0
      ]
    ]
  Velocity:
    transitions: 
      Passive: LT + B.on_pressed
      Mimic_Action_1: LT(2s) + down.on_pressed
      Mimic_Action_2: LT(2s) + left.on_pressed
      Mimic_Action_3: LT(2s) + right.on_pressed
    policy_dir: ../../../logs/rsl_rl/arcus_a1_v0_il_velocity

  Mimic_Action_1:
    transitions: 
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
    fps: 60
    motion_file: ../../../mocap/arcus/actors/22.csv
    policy_dir: ../../../logs/rsl_rl/arcus_a1_v0_mimic
    time_start: 0
    time_end: 24.0

  Mimic_Action_2:
    transitions: 
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
    fps: 60
    motion_file: ../../../mocap/arcus/actors/1311.csv
    policy_dir: ../../../logs/rsl_rl/arcus_a1_v0_mimic
    time_start: 0
    time_end: 24.0

  Mimic_Action_3:
    transitions: 
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
    fps: 60
    motion_file: ../../../mocap/arcus/actors/1011.csv
    policy_dir: ../../../logs/rsl_rl/arcus_a1_v0_mimic
    time_start: 0
    time_end: 24.0